# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 23:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sos',
            name='latitiude',
        ),
        migrations.RemoveField(
            model_name='sos',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='sos',
            name='updated',
        ),
        migrations.AddField(
            model_name='sos',
            name='location_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
