# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160306_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sos',
            name='location_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
