# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_sos_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sos',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
