# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160306_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.BigIntegerField(),
        ),
    ]
