# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160306_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='sos',
            name='note_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
